### ISSUE TITLE
Too many dependancies in requirements

### ISSUE THREAD

**Issue by pmithrandir** [Wouterkoorn/sqlalchemy-pydantic-orm#2]
Hello,

Checking the module, I think the requirement is very detailled, including dependancies that are indirect.

I think the needed one are : 
pydantic
sqlalchemy
flake8
setuptools
pytest

What's your insight ?

regards,
Pierre

**Comment by Wouterkoorn** [comment]
Hi Pierre, thank you for you input.

I don't think there is a need for a requirements.txt file at all, unless I'm forgetting something (it has been over a year). I'll likely just use the setup.py, or better, pyproject.toml for the loose requirements.

**Comment by pmithrandir** [comment]
Hi,

I'm not sure, but when I'm running pip install from your version, I'm downgraded to the requirements version listed in that file.

My PR intend to remove that issue.
